IF
Global("ANbanditsxists","AR0406",0)
GlobalGT("ANkors","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("ANbanditsxists","AR0406",1)
CreateCreature("ANband1",[1536.1910],0)
CreateCreature("ANband2",[1535.1906],10)
Continue()
END

IF
OnCreation()
Global("ANbanditsxists","AR0406",2)
OR(2)
Exists("ANband1")
Exists("ANband2")
THEN
RESPONSE #100
ActionOverride("ANband1",DestroySelf())
ActionOverride("ANband2",DestroySelf())
END