IF
Global("ANbanditsxists","AR0400",0)
Global("ANkors","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("ANbanditsxists","AR0400",1)
CreateCreature("ANband1",[1536.1910],0)
CreateCreature("ANband2",[1535.1906],10)
Continue()
END

IF
OnCreation()
Global("ANkors","GLOBAL",3)
OR(2)
Exists("ANband1")
Exists("ANband2")
THEN
RESPONSE #100
ActionOverride("ANband1",DestroySelf())
ActionOverride("ANband2",DestroySelf())
Continue()
END