IF 
Global("ANStashRenalJOB","GLOBAL",12)
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
Global("ANStashEdwinGraveTalk","AR0800",0)

THEN
  RESPONSE #100
SetGlobal("ANStashEdwinGraveTalk","AR0800",1)
RealSetGlobalTimer("ANStashGraveTalkTimer","AR0800",10)
END

IF 
RealGlobalTimerExpired("ANStashGraveTalkTimer","AR0800")
Global("ANStashEdwinGraveTalk","AR0800",1)

THEN
  RESPONSE #100
ActionOverride(Player1,StartDialog("Player1",Myself))
END