IF
Global("AranKorganToB","GLOBAL",1)
RealGlobalTimerExpired("ANAranLetterKorganTimer","GLOBAL")
InParty(Myself) 
!Dead("Korgan")
!StateCheck(Myself,CD_STATE_NOTVALID)
See(Player1)
CombatCounter(0)
!See([ENEMY])
THEN
	RESPONSE #100
	   SetGlobal("AranKorganToB","GLOBAL",2)
       ActionOverride(Player1,SetDialog("PLAYER1"))
       SmallWait(3)
       ActionOverride(Myself,Dialog(Player1))
END