IF
Global("AranSarevokToB","GLOBAL",1)
RealGlobalTimerExpired("ANAranLetterSarevokTimer","GLOBAL")
InParty(Myself) 
!Dead("Sarevok")
!StateCheck(Myself,CD_STATE_NOTVALID)
See(Player1)
CombatCounter(0)
!See([ENEMY])
THEN
	RESPONSE #100
	   SetGlobal("AranSarevokToB","GLOBAL",2)
       ActionOverride(Player1,SetDialog("PLAYER1"))
       SmallWait(3)
       ActionOverride(Myself,Dialog(Player1))
END